### ISSUE TITLE
Sinch Package Dependency

### ISSUE THREAD

**Issue by ghost** [sinch/nuget-sinch.verification#1]
I am getting this error while adding Sinch.Verification in my project.

_Package Sinch.Verification 0.9.2 is not compatible with portable45-net45+win8+wpa81 (.NETPortable,Version=v4.5,Profile=Profile111). Package Sinch.Verification 0.9.2 supports: net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with .NETPortable,Version=v4.5,Profile=Profile111._

**Comment by spacedsweden** [comment]
this should work now but for 4.6
